C FILL AN INTEGER ARRAY OF THE STATED SIZE WITH THE GIVEN VALUE
      SUBROUTINE AIFILL(ARRAY, SIZE, VAL)
      INTEGER ARRAY(*), SIZE, VAL
      DO 10 I=1,SIZE
      ARRAY(I) = VAL
10    CONTINUE
      END

C INITIALIZE AN INTEGER ARRAY OF THE STATED SIZE WITH ZERO
      SUBROUTINE AIZERO(ARRAY, SIZE)
      INTEGER ARRAY(*), SIZE
      CALL AIFILL(ARRAY, SIZE, 0)
      END

C RETURN TRUE IF THE INTEGER ARRAY OF THE STATED SIZE CONTAINS THE
C GIVEN VALUE
      LOGICAL FUNCTION AICONT(ARRAY, SIZE, VAL)
      INTEGER ARRAY(*), SIZE, VAL, I
      AICONT = .FALSE.
      I=1
20    IF (I .GT. SIZE) GOTO 40
      IF (ARRAY(I) .EQ. VAL) GOTO 30
      I = I + 1
      GOTO 20
30    AICONT = .TRUE.
40    RETURN
      END

C RETURN TRUE IF THE SORTED INTEGER ARRAY OF THE STATED SIZE 
C CONTAINS THE GIVEN VALUE. NOTE THAT WE NEED TO BE CAREFUL
C WHEN THE MIDPOINT OF THE BINARY SEARCH ENDS UP EQUAL TO ONE
C OF THE ENDPOINTS. WE CHECK WHETHER THE DIFFERENCE IS LESS
C THAN OR EQUAL TO 1.
      LOGICAL FUNCTION AICONS(ARRAY, SIZE, VAL)
      INTEGER ARRAY(*), SIZE, VAL, I, FIRST, LAST, MID
      AICONS = .FALSE.
      FIRST = 1
      LAST = SIZE
50    IF (LAST - FIRST .LE.1) GOTO 80
      MID = (FIRST + LAST) / 2
      IF (ARRAY(MID) - VAL) 60, 90, 70
60    FIRST = MID
      GOTO 50
70    LAST = MID
      GOTO 50
80    IF ((ARRAY(FIRST) .NE. VAL) .AND. (ARRAY(LAST) .NE. VAL)) GOTO 100
90    AICONS = .TRUE.
100   RETURN
      END
