C ARRAY PREDICATES

C SORTDP RETURNS .TRUE. IF ARRAY IS SORTED, OTHERWISE .FALSE.
      LOGICAL FUNCTION SORTDP(ARRAY, SIZE)
      INTEGER ARRAY(*), SIZE, I
      SORTDP = .TRUE.
      DO 10 I=1,SIZE-1
      IF (ARRAY(I) .GT. ARRAY(I+1)) SORTDP = .FALSE.
10    CONTINUE
      END
