C     CNTDIV RETURNS THE NUMBER OF DIVISORS OF THE GIVEN POSITIVE
C     INTEGER. CNTDIV(10) = 4
      INTEGER FUNCTION CNTDIV(I)
      INTEGER I, J
      LOGICAL DIVIDP
      CNTDIV=1
      DO 10 J=1,I/2
      IF (DIVIDP(I,J)) CNTDIV = CNTDIV + 1
10    CONTINUE
      RETURN
      END
