C     LTOI TAKES A LOGICAL VALUE AND RETURNS 0 IF IT IS TRUE AND 1 IF IT IS FALSE
      INTEGER FUNCTION LTOI(L)
      LOGICAL L
      IF (L) LTOI = 0
      IF (.NOT. L) LTOI = 1
      RETURN
      END


