C NUMBER PREDICATES

C DIVIDP RETURNS .TRUE. IF I2 DIVIDES I1, OTHERWISE .FALSE.
      LOGICAL FUNCTION DIVIDP(I1, I2)
      INTEGER I1, I2
      DIVIDP = MOD(I1, I2) .EQ. 0
      RETURN
      END

C EVENP RETURNS .TRUE. IF THE INTEGER PASSED IS EVEN, OTHERWISE .FALSE.
      LOGICAL FUNCTION EVENP(I)
      LOGICAL DIVIDP
      INTEGER I
      EVENP = DIVIDP(I, 2)
      RETURN
      END

C PRIMEP RETURNS .TRUE. IF I IS PRIME, OTHERWISE FALSE.
      LOGICAL FUNCTION PRIMEP(I)
      INTEGER I, T
      REAL SQRTI
      LOGICAL EVENP, DIVIDP
      PRIMEP = I .GT. 1
      IF ((I .EQ. 2) .OR. 
     1 (I .EQ. 3) .OR. 
     2 (I .EQ. 5) .OR. 
     3 (I .EQ. 7)) GOTO 100
      IF ((EVENP(I)) .OR. 
     1 (DIVIDP(I, 3)) .OR. 
     2 (DIVIDP(I, 5)) .OR. 
     3 (DIVIDP(I, 7))) PRIMEP = .FALSE.
      SQRTI = SQRT(I * 1.0)
      T = 7
10    T = T + 4
      IF (.NOT. PRIMEP) GOTO 100
      IF (T .GT. SQRTI) GOTO 100
      IF (DIVIDP(I, T)) PRIMEP = .FALSE.
      T = T + 2
      IF (.NOT. PRIMEP) GOTO 100
      IF (T .GT. SQRTI) GOTO 100
      IF (DIVIDP(I, T)) PRIMEP = .FALSE.
      GOTO 10
100   RETURN
      END
