C POPULATE ARRAY WITH NUMBERS FROM 1 TO SIZE
      SUBROUTINE POPLIN(ARRAY, SIZE)
      INTEGER ARRAY(*), SIZE, I
      DO 10 I=1,SIZE
      ARRAY(I) = I
10    CONTINUE
      END

C POPULATE ARRAY WITH SQUARES OF NUMBERS FROM 1 TO SIZE
      SUBROUTINE POPSQU(ARRAY, SIZE)
      INTEGER ARRAY(*), SIZE, I
      DO 20 I=1,SIZE
      ARRAY(I) = I*I
20    CONTINUE
      END

C POPULATE ARRAY WITH CUBES OF NUMBERS FROM 1 TO SIZE
      SUBROUTINE POPCUB(ARRAY, SIZE)
      INTEGER ARRAY(*), SIZE, I
      DO 30 I=1,SIZE
      ARRAY(I) = I*I*I
30    CONTINUE
      END
