      PROGRAM PROBLEM9
      INTEGER I, RES, WAYS
      DO 10 I=1,30
      RES = WAYS(I)
      PRINT *, I, RES
10    CONTINUE
      END

C CALCULATE THE NUMBER OF WAYSOF MAKING THE TARGET AS A SUM OF ODD
C INTEGERS ALL LESS THAN OR EQUAL TO THE TARGET
      INTEGER FUNCTION WAYS(TARGET) 
      INTEGER TARGET
C NODD = NUMBER OF ODD NUMBERS LESS THAN OR EQUAL TO TARGET
      INTEGER NODD
      INTEGER WAYS1
      NODD = (TARGET + 1) / 2
      WAYS = WAYS1(TARGET, NODD)      
      END

      INTEGER FUNCTION WAYS1(TARGET, NODD)
      INTEGER TARGET, NODD
      INTEGER ODDS(NODD), COEFFS(NODD), MAXES(NODD)
      INTEGER I, SUM
      LOGICAL ISDONE
C      PRINT *, "TARGET", TARGET
      DO 20 I=1,NODD
      ODDS(I) = (2 * I) - 1
      MAXES(I) = TARGET / ODDS(I)
      COEFFS(I) = 0
20    CONTINUE
C      CALL AIDUMP(MAXES, NODD)
      ISDONE = .FALSE.
      WAYS1 = 0
30    CALL CNTL(COEFFS, MAXES, NODD, ISDONE)
      IF (ISDONE) GOTO 60
      SUM = 0
      DO 40, I=1,NODD
      SUM = SUM + COEFFS(I) * ODDS(I)
40    CONTINUE
      IF (SUM .NE. TARGET) GOTO 50
      WAYS1 = WAYS1 + 1
50    GOTO 30
60    END    
