      PROGRAM PROBLEM9
      INTEGER I, RES, WAYS
      DO 10 I=1,30
      RES = WAYS(I)
      PRINT *, I, RES
10    CONTINUE
      END

C CALCULATE THE NUMBER OF WAYSOF MAKING THE TARGET AS A SUM OF ODD
C INTEGERS ALL LESS THAN OR EQUAL TO THE TARGET
      INTEGER FUNCTION WAYS(TARGET) 
      INTEGER TARGET
C NODD = NUMBER OF ODD NUMBERS LESS THAN OR EQUAL TO TARGET
      INTEGER NODD
      INTEGER WAYS1
      NODD = (TARGET + 1) / 2
      WAYS = WAYS1(TARGET, NODD)      
      END

      INTEGER FUNCTION WAYS1(TARGET, NODD)
      INTEGER TARGET, NODD
      INTEGER ODDS(NODD), COEFFS(NODD), MAXES(NODD)
      INTEGER I, J, SUM, T, HODD
      LOGICAL ISDONE
C      PRINT *, "TARGET", TARGET
      DO 20 I=1,NODD
      ODDS(I) = (2 * I) - 1
20    CONTINUE
      WAYS1 = 0
C IF THE TARGET IS ODD AND THEREFORE EQUAL TO THE HIGHEST ODD NUMBER
C THEN COUNT THAT AS ONE WAY
      IF (ODDS(NODD) .EQ. TARGET) WAYS1 = 1
      DO 55 J=NODD,1,-1
      HODD = ODDS(J)
      T = TARGET - HODD
C      PRINT *, "HODD", HODD, "T", T
C NEED TO MAKE T USING NUMBERS SMALLER THAN OR EQUAL TO HODD (THE
C HIGHEST ODD NUMBER)
      DO 29 I=1,NODD
C FOR ALL ODD NUMBERS SMALLER THAN THE MAXIMUM WE'RE CONSIDERING, WORK
C OUT THE MAXIMUM NUMBER OF EACH THAT COULD PLAUSIBLY BE NEEDED IN THE
C SUM. SET ALL COEFFICIENTS TO ZERO
      IF (ODDS(I) .GT. HODD) GOTO 25
      MAXES(I) = T / ODDS(I)
      GOTO 28
25    MAXES(I) = 0
28    COEFFS(I) = 0
29    CONTINUE
      ISDONE = .FALSE.
30    CALL CNTL(COEFFS, MAXES, J, ISDONE)
      IF (ISDONE) GOTO 55
      SUM = 0
C HAVE WE FOUND A COMBINATION OF COEFFICIENTS THAT MULTIPLY BY THEIR
C RESPECTIVE ODD NUMBERS TO GIVE US THE REDUCED TARGET T?
      DO 40, I=1,NODD
      SUM = SUM + COEFFS(I) * ODDS(I)
40    CONTINUE
      IF (SUM .NE. T) GOTO 50
      WAYS1 = WAYS1 + 1
50    GOTO 30
55    CONTINUE
60    END    
