      PROGRAM PROBLEM10
      INTEGER I, SUM, SUMDIV
      DO 10 I=1,200
      SUM = SUMDIV(I)
      PRINT *, I, SUM
10    CONTINUE
      END

C CALCULATE THE SUM OF ALL DIVISORS OF THE TARGET (NOT INCLUDING 
C TARGET I.E. SUM OF DIVISORS OF 28 IS 28)
      INTEGER FUNCTION SUMDIV(TARGET) 
      INTEGER TARGET
      LOGICAL DIVIDP
      SUMDIV = 0
      DO 20 I=1, TARGET - 1
      IF (DIVIDP(TARGET, I)) SUMDIV = SUMDIV + I
20    CONTINUE
      END
