      PROGRAM PROBLEM11
      INTEGER I, SUM, PHI
      DO 10 I=1,200
      PRINT *, I, PHI(I)
10    CONTINUE
      END

C CALCULATE NUMBER OF NUMBERS SMALLER THAN TARGET WHICH ARE RELATIVELY
C PRIME TO IT
      INTEGER FUNCTION PHI(TARGET) 
      INTEGER TARGET, I, TEST
      LOGICAL DIVSRS(TARGET - 1)
      LOGICAL DIVIDP
C MAKE A NOTE OF ALL DIVISORS OF TARGET
      DO 20 I=1, TARGET - 1
      DIVSRS(I) = DIVIDP(TARGET, I)
20    CONTINUE
      PHI=0
      DO 50 I=2, TARGET - 1
      TEST = 2
30    IF (TEST .GT. I) GOTO 40
      IF (DIVIDP(I, TEST) .AND. DIVSRS(TEST)) GOTO 50
      TEST = TEST + 1
      GOTO 30
40    PHI = PHI + 1
50    CONTINUE
      END
