      PROGRAM PROBLEM6
      CALL QUAR2(3)
      CALL QUAR2(5)
      CALL QUAR2(7)
      CALL QUAR2(11)
      CALL QUAR2(17)
      CALL QUAR2(29)
      CALL QUAR2(61)
      END

C A NUMBER N IS A QUADRATIC RESIDUE MODULO P IF P DND N AND THERE IS
C A NUMBER M (1 <= M < PRIME) SUCH THAT PRIME DIVIDES M^2 - N
      SUBROUTINE QUARES(PRIME)
      INTEGER PRIME
C NUMBER TO TEST FOR BEING A QUADRATIC RESIDUE
      INTEGER N
      LOGICAL QURESP
      PRINT *, "QUADRATIC RESIDUES MODULO ", PRIME
      DO 10 N=1,PRIME-1
      IF (QURESP(N, PRIME)) PRINT *, N
10    CONTINUE
      END
   

      LOGICAL FUNCTION QURESP(N, P)
      INTEGER N, P, M
      LOGICAL DIVIDP
      QURESP = .FALSE.
      M = 1
100   IF (DIVIDP(M*M - N, P)) GOTO 110
      M = M + 1
      IF (M .EQ. P) GOTO 120
      GOTO 100
110   QURESP = .TRUE.
120   END
      

C A NUMBER N IS A QUADRATIC RESIDUE MODULO P IF P DND N AND THERE IS
C A NUMBER M (1 <= M < PRIME) SUCH THAT PRIME DIVIDES M^2 - N
      SUBROUTINE QUAR2(PRIME)
      INTEGER PRIME
      INTEGER N
      INTEGER RESID(PRIME)
      INTEGER AIDDUP, LAST
      LOGICAL QURESP
      PRINT *, "QUADRATIC RESIDUES MODULO ", PRIME
      DO 10 N=1,PRIME-1
      RESID(N) = MOD(N * N, PRIME)
      PRINT *, RESID(N)
10    CONTINUE
      LAST = AIDDUP(RESID, PRIME - 1)
      PRINT *, "LAST UNIQUE ", LAST
      END
