      SUBROUTINE IXPECT(TESTNO, TESTSUBNO, RESULT, XPECTD)
      INTEGER TESTNO, TESTSUBNO, RESULT, XPECTD
      IF (RESULT - XPECTD) 110, 120, 130
110   PRINT *, "FAIL ", TESTNO, TESTSUBNO, RESULT, "LT", XPECTD
      GOTO 140
120   PRINT *, "PASS ", TESTNO, TESTSUBNO, RESULT, "=", XPECTD
      GOTO 140
130   PRINT *, "FAIL ", TESTNO, TESTSUBNO, RESULT, "GT", XPECTD
140   END

      SUBROUTINE LXPECT(TESTNO, TESTSUBNO, RESULT, XPECTD)
      INTEGER TESTNO, TESTSUBNO
      LOGICAL RESULT, XPECTD
      IF (XPECTD) GOTO 220
      IF (RESULT) GOTO 210
      PRINT *, "PASS ", TESTNO, TESTSUBNO, RESULT, "EQ", XPECTD
      GOTO 290
210   PRINT *, "FAIL ", TESTNO, TESTSUBNO, RESULT, "NE", XPECTD
      GOTO 290
220   IF (RESULT) GOTO 230
      PRINT *, "FAIL ", TESTNO, TESTSUBNO, RESULT, "NE", XPECTD
      GOTO 290
230   PRINT *, "PASS ", TESTNO, TESTSUBNO, RESULT, "EQ", XPECTD
290   END
