      SUBROUTINE IXPECT(TESTNO, TESTSUBNO, RESULT, XPECTD)
      INTEGER TESTNO, TESTSUBNO, RESULT, XPECTD
      IF (RESULT - XPECTD) 110, 120, 130
110   PRINT *, "FAIL ", TESTNO, TESTSUBNO, RESULT, "LT", XPECTD
      GOTO 140
120   PRINT *, "PASS ", TESTNO, TESTSUBNO, RESULT, "=", XPECTD
      GOTO 140
130   PRINT *, "FAIL ", TESTNO, TESTSUBNO, RESULT, "GT", XPECTD
140   END
