      PROGRAM TESTICTNS
      CALL TEST1(1)
      END

      SUBROUTINE TEST1(T)
      INTEGER T, NUMS(3), NZLEN, CNT
      LOGICAL ISDONE
      ISDONE = .FALSE.
      CALL AIZERO(NUMS, 3)
      NZLEN = 0
      CNT = 0
1     CALL ICTNS(NUMS, 3, 2, NZLEN, ISDONE)
      CNT = CNT + 1
      IF (ISDONE) GOTO 3
      GOTO 1
3     CALL IXPECT(T, 1, CNT, 15)
      END
