      PROGRAM TESTICTNS
      INTEGER NUMS(5), NZLEN
      LOGICAL ISDONE
      ISDONE = .FALSE.
      CALL AIZERO(NUMS, 5)
      NZLEN = 0
1     PRINT *, NUMS(1), NUMS(2), NUMS(3), NUMS(4), NUMS(5), NZLEN
      CALL ICTNS(NUMS, 5, 10, NZLEN, ISDONE)
      IF (ISDONE) GOTO 3
      GOTO 1
3     END
